vim.keymap.set('n', '<leader>o', ':update<CR> :source<CR>')
vim.keymap.set('n', '<leader>w', ':write<CR>')
vim.keymap.set('n', '<leader>p', '"_dP')
vim.keymap.set('n', '<c+u>', '<c+u>zz')
vim.keymap.set('n', '<M-j>', 'ddp')
vim.keymap.set('n', '<M-k>', 'ddkP')
vim.keymap.set({ 'n', 'v', 'x' }, '<leader>y', '"+y')
vim.keymap.set({ 'n', 'v', 'x' }, '<leader>d', '"+d')
vim.keymap.set('n', '<Esc>', ':nohlsearch<CR>')
vim.keymap.set('n', '<leader>sf', FzfLua.files, { desc = "Search Files in project" })
vim.keymap.set('n', '<leader>sg', FzfLua.grep, { desc = "Search with ripGrep project" })
vim.keymap.set('n', '<leader>sk', FzfLua.keymaps, { desc = "Search Keymaps" })
vim.keymap.set('n', '<leader>sq', FzfLua.quickfix, { desc = "Search Quickfix" })
vim.keymap.set('n', '<leader>sc', FzfLua.lsp_document_symbols, { desc = "Search Code in document" })
vim.keymap.set('n', '<leader>sw', FzfLua.lsp_workspace_symbols, { desc = "Search code in Workspace" })
vim.keymap.set('n', '<leader>de', FzfLua.lsp_document_diagnostics, { desc = "Diagnostics Errors" })
vim.keymap.set('n', '<leader>dw', FzfLua.lsp_workspace_diagnostics, { desc = "Diagnostics erros in Workspace" })
vim.keymap.set('n', '<leader>h', FzfLua.helptags, { desc = "Get Help" })
vim.keymap.set('n', '<leader>e', ":Oil<CR>", { desc = "Open Oil" })
vim.keymap.set('n', '<leader>f', vim.lsp.buf.format, { desc = "Format buffer" })
vim.keymap.set('n', '<leader>cr', vim.lsp.buf.rename, { desc = "Rename symbol" })
vim.keymap.set('n', '<leader>ca', FzfLua.lsp_code_actions, { desc = "Code action" })
vim.keymap.set('n', '<leader>up', vim.pack.update, { desc = "Update Plugins" })
vim.keymap.set('n', 'gd', FzfLua.lsp_definitions)
vim.keymap.set('n', 'gr', FzfLua.lsp_references)
vim.keymap.set('n', 'gi', FzfLua.lsp_implementations)
